# Generated by Django 4.2.11 on 2024-04-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agriculture_App', '0002_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='Area',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
