# Generated by Django 4.2.11 on 2024-04-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agriculture_App', '0003_userdetails_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registeratio_number', models.TextField(default=None, max_length=100)),
                ('College', models.TextField(default=None, max_length=100)),
                ('Year', models.TextField(default=None, max_length=100)),
                ('Name', models.TextField(default=None, max_length=100)),
                ('Picture', models.ImageField(null=True, upload_to='images/')),
                ('username', models.TextField(default=None, max_length=100)),
                ('password', models.TextField(default=None, max_length=100)),
                ('Age', models.TextField(default=None, max_length=100)),
                ('Gender', models.TextField(default=None, max_length=100)),
                ('Phone', models.TextField(default=None, max_length=100)),
                ('Area', models.TextField(default=None, max_length=100)),
                ('State', models.TextField(default=None, max_length=100)),
                ('City', models.TextField(default=None, max_length=100)),
                ('Address', models.TextField(default=None, max_length=100)),
                ('Start_time', models.DateTimeField(default=None, max_length=100, null=True)),
                ('End_Time', models.DateTimeField(default=None, max_length=100, null=True)),
                ('Speciality', models.TextField(default=None, max_length=100)),
                ('Type_of_medicine', models.TextField(default=None, max_length=100)),
                ('Permission', models.TextField(default=None, max_length=100, null=True)),
                ('Disease_treated', models.TextField(default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Doctor',
            },
        ),
    ]
