# Generated by Django 4.2.11 on 2024-04-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agriculture_App', '0006_doctor_feedback_user_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_feedback',
            name='doctor',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor_feedback',
            name='feedback',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doctor_feedback',
            name='response',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user_feedback',
            name='feedback',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user_feedback',
            name='response',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user_feedback',
            name='user',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
